/**
 * Generates dist/tokens.css for the web app (Tailwind v4):
 *  - :root / .dark custom properties (RGB channels)
 *  - an `@theme inline` block mapping them to Tailwind color/radius utilities
 */
import { mkdirSync, writeFileSync } from 'node:fs';
import { dirname, join } from 'node:path';
import { fileURLToPath } from 'node:url';

import { colorTokenNames, cssVars } from '../src/colors';
import { radius } from '../src/scale';

const outFile = join(dirname(fileURLToPath(import.meta.url)), '..', 'dist', 'tokens.css');

const block = (selector: string, vars: Record<string, string>) =>
  `${selector} {\n${Object.entries(vars)
    .map(([k, v]) => `  ${k}: ${v};`)
    .join('\n')}\n}`;

const themeVars: Record<string, string> = {
  ...Object.fromEntries(colorTokenNames.map((n) => [`--color-${n}`, `rgb(var(--${n}))`])),
  '--radius-sm': radius.sm,
  '--radius-md': radius.md,
  '--radius-lg': radius.lg,
  '--radius-xl': radius.xl,
  '--radius-2xl': radius['2xl'],
};

const css = [
  '/* Generated by @cp/design-tokens — do not edit. Source: packages/design-tokens/src */',
  block(':root', { ...cssVars('light'), '--radius': radius.lg }),
  block('.dark', cssVars('dark')),
  block('@theme inline', themeVars),
  '',
].join('\n\n');

mkdirSync(dirname(outFile), { recursive: true });
writeFileSync(outFile, css);
console.log(`design-tokens: wrote ${outFile}`);
