/**
 * Shared types. `database.ts` (generated by `pnpm db:types`) is added in Phase 2.
 */

/** Mirrors the `Json` type emitted by `supabase gen types`. */
export type Json = string | number | boolean | null | { [key: string]: Json | undefined } | Json[];

/** Nominal typing helper, e.g. `type VehicleId = Brand<string, 'VehicleId'>`. */
export type Brand<T, B extends string> = T & { readonly __brand: B };

/** Result shape returned by every mutation (Server Actions and mobile mutations). */
export type ActionResult<T> =
  { ok: true; data: T } | { ok: false; error: string; fieldErrors?: Record<string, string[]> };
