/**
 * Shared types. `database.ts` is GENERATED by `pnpm db:types` — never edit it by hand.
 */
export {
  Constants,
  type CompositeTypes,
  type Database,
  type Enums,
  type Json,
  type Tables,
  type TablesInsert,
  type TablesUpdate,
} from './database';

/** Nominal typing helper, e.g. `type VehicleId = Brand<string, 'VehicleId'>`. */
export type Brand<T, B extends string> = T & { readonly __brand: B };

/** Result shape returned by every mutation (Server Actions and mobile mutations). */
export type ActionResult<T> =
  { ok: true; data: T } | { ok: false; error: string; fieldErrors?: Record<string, string[]> };
