export { listFeatures, listMakes, listModels } from './catalog';
export type { AppSupabaseClient } from './client';
export {
  createFeature,
  createMake,
  createModel,
  deleteCatalogEntry,
  listCatalog,
  listUsers,
  setUserRole,
  updateSiteSettings,
  type AdminUser,
  type CatalogData,
  type UserListOptions,
} from './console-admin';
export {
  addDealerMember,
  applyAsDealer,
  DEALER_ASSETS_BUCKET,
  DEALER_DOCS_BUCKET,
  dealerDocumentPath,
  dealerDocumentSchema,
  dealerDocumentUrls,
  dealerLogoUrl,
  getConsoleDealer,
  getDealerTeam,
  listDealersForAdmin,
  moderateDealer,
  removeDealerMember,
  updateDealerMemberRole,
  updateDealerProfile,
  uploadDealerDocument,
  uploadDealerLogo,
  type AdminDealerRow,
  type ConsoleDealer,
  type DealerDocument,
  type DealerListFilters,
  type TeamMember,
} from './console-dealers';
export {
  consoleQueries,
  invalidateInventory,
  useAdminDealers,
  useConsoleDealer,
  useConsoleVehicle,
  useConsoleVehicles,
  useModerateDealer,
  useSaveVehicle,
  useSetVehicleStatus,
  useUpdateVehiclePrice,
  useVehiclePhotos,
} from './console-queries';
export {
  addVehicleImages,
  bulkUpdateVehicles,
  CONSOLE_PAGE_SIZE,
  CONSOLE_SORTS,
  createPhotoUpload,
  createVehicle,
  decodeVin,
  deleteVehicle,
  deleteVehicleImage,
  getConsoleVehicle,
  listConsoleVehicles,
  reorderVehicleImages,
  setVehicleFeatures,
  setVehicleStatus,
  updateVehicle,
  updateVehiclePrice,
  uploadPhoto,
  vinDecodeSchema,
  type BulkVehiclePatch,
  type ConsoleSort,
  type ConsoleVehicle,
  type ConsoleVehicleDetail,
  type ConsoleVehicleFilters,
  type ConsoleVehicleImage,
  type InventoryScope,
  type PhotoUploadTarget,
  type UploadedPhoto,
  type VinDecodeResult,
} from './console-vehicles';
export { getDealerBySlug, getHouseDealer } from './dealers';
export { getFacets, inventoryFacetsSchema, toFacetPayload, type InventoryFacets } from './facets';
export { addFavorite, listFavoriteIds, mergeFavorites, removeFavorite } from './favorites';
export {
  catalogQueries,
  dealerQueries,
  favoriteQueries,
  settingsQueries,
  useFacets,
  useFavoriteIds,
  useInfiniteVehicles,
  useMakes,
  useSiteSettings,
  useToggleFavorite,
  useVehicle,
  useVehicles,
  useVehiclesByIds,
  vehicleQueries,
} from './queries';
export { queryKeys } from './query-keys';
export { getSessionContext, type DealerMembership, type SessionContext } from './session';
export { getSiteSettings, type SiteSettings } from './settings';
export { VEHICLE_IMAGES_BUCKET, vehicleImageUrl } from './storage';
export { recordVehicleView, trackContactClick } from './tracking';
export {
  DEFAULT_PAGE_SIZE,
  getVehicleBySlug,
  getVehiclesByIds,
  listFeaturedVehicles,
  listVehicles,
  STOREFRONT_STATUSES,
  type VehicleCard,
  type VehicleDetail,
  type VehiclePage,
} from './vehicles';
